In [246]:
import pandas as pd
df = pd.read_csv('/content/my_file (1).csv')

In [247]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [249]:
df.sample()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]

In [250]:
df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='object')

In [251]:
df.shape

(20, 11)

In [252]:
import unicodedata

df.columns = (
    df.columns.map(lambda x: unicodedata.normalize('NFKD', x).encode('ascii', 'ignore').decode('utf-8'))
    .str.lower()
    .str.strip()
    .str.replace(r'[^a-z0-9_ ]', '', regex=True)
    .str.replace(r'\s+', '_', regex=True)
)

In [253]:
df.rename(columns={'actualgross':'actual_gross', 'adjustedgross_in_2022_dollars':'gross_2012'},inplace=True)

df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [254]:
df.isna().sum()

rank                               0
peak                              11
all_time_peak                     14
actual_gross                       0
adjusted_gross_in_2022_dollars     0
artist                             0
tour_title                         0
years                              0
shows                              0
average_gross                      0
ref                                0
dtype: int64

In [255]:
df.drop(columns=['peak','all_time_peak'],inplace=True)
df

,rank,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref
0,1,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [256]:
for i in range(df.shape[0]):
  df['actual_gross'].values[i] = df['actual_gross'].str.strip().str.replace(r'[a-z ]','',regex=True).values[i][1:12]


df['actual_gross']

0     780,000,000
1     579,800,000
2     411,000,000
3     397,300,000
4     345,675,146
5     305,158,363
6     280,000,000
7     257,600,000
8     256,084,556
9     250,400,000
10    229,100,000
11    227,400,000
12    204,000,000
13    200,000,000
14    194,000,000
15    184,000,000
16    170,000,000
17    169,800,000
18    167,700,000
19    150,000,000
Name: actual_gross, dtype: object

In [257]:
for i in range(df.shape[0]):
  df['adjusted_gross_in_2022_dollars'].values[i] = df['adjusted_gross_in_2022_dollars'].str.strip().str.replace(r'[a-z ]','',regex=True).values[i][1:]


df['adjusted_gross_in_2022_dollars']

0     780,000,000
1     579,800,000
2     560,622,615
3     454,751,555
4     402,844,849
5     388,978,496
6     381,932,682
7     257,600,000
8     312,258,401
9     309,141,878
10    283,202,896
11    295,301,479
12    251,856,802
13    299,676,265
14    281,617,035
15    227,452,347
16    213,568,571
17    207,046,755
18    204,486,106
19    185,423,109
Name: adjusted_gross_in_2022_dollars, dtype: object

In [258]:
for i in range(df.shape[0]):
  df['average_gross'].values[i] = df['average_gross'].str.strip().str.replace(r'[a-z ]','',regex=True).values[i][1:]


df['average_gross']

0     13,928,571
1     10,353,571
2      4,835,294
3      2,546,795
4      6,522,173
5      3,467,709
6      2,137,405
7      6,282,927
8      5,226,215
9      2,945,882
10     1,735,606
11     1,118,227
12     1,350,993
13       615,385
14     3,233,333
15     1,295,775
16     1,734,694
17     2,070,732
18     1,385,950
19     1,744,186
Name: average_gross, dtype: object

In [259]:
df

,rank,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"13,928,571",[1]
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"10,353,571",[3]
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"4,835,294",[6]
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"2,546,795",[7]
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"6,522,173",[8]
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"3,467,709",[9]
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"2,137,405",[11]
7,7,"257,600,000","257,600,000",Pink,Summer Carnival †,2023–2024,41,"6,282,927",[12]
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"5,226,215",[13]
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"2,945,882",[14]
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"1,735,606",[15][16]
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"1,118,227",[18]
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"1,350,993",[19]
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"615,385",[20]
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"3,233,333",[5]
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"1,295,775",[22]
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"1,734,694",[d]
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"2,070,732",[4]
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"1,385,950",[25]
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"1,744,186",[26]

In [260]:
df['ref'] = df['ref'].str.extract(r'(\d+)').astype(float)

df['ref']

0      1.0
1      3.0
2      6.0
3      7.0
4      8.0
5      9.0
6     11.0
7     12.0
8     13.0
9     14.0
10    15.0
11    18.0
12    19.0
13    20.0
14     5.0
15    22.0
16     NaN
17     4.0
18    25.0
19    26.0
Name: ref, dtype: float64

In [261]:
df['tour_title'] = df['tour_title'].str.replace(r'[^a-zA-Z\s]', '', regex=True).str.strip()
df['tour_title']

0                        The Eras Tour
1               Renaissance World Tour
2                 Sticky  Sweet Tour a
3          Beautiful Trauma World Tour
4              Reputation Stadium Tour
5                        The MDNA Tour
6            Taking Chances World Tour
7                      Summer Carnival
8             The Formation World Tour
9                      The  World Tour
10      The Mrs Carter Show World Tour
11               The Monster Ball Tour
12                Prismatic World Tour
13    Living Proof The Farewell Tour a
14                    Confessions Tour
15           The Truth About Love Tour
16                  Born This Way Ball
17                    Rebel Heart Tour
18                          Adele Live
19                        The Red Tour
Name: tour_title, dtype: object

In [262]:
def parse_years(year_str):
    if isinstance(year_str, str):
        years = year_str.replace('–', '-').split('-')
        if len(years) == 1:
            start_year = int(years[0].strip())
            end_year = start_year
        else:
            start_year = int(years[0].strip())
            end_year = int(years[1].strip())
        return start_year, end_year
    return None, None

df[['start_year', 'end_year']] = df['years'].apply(lambda x: pd.Series(parse_years(x)))

df.drop(columns=['years'], inplace=True)
df[['start_year', 'end_year']].head()

   start_year  end_year
0        2023      2024
1        2023      2023
2        2008      2009
3        2018      2019
4        2018      2018

In [263]:
df

,rank,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,shows,average_gross,ref,start_year,end_year
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,56,"13,928,571",1.0,2023,2024
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,56,"10,353,571",3.0,2023,2023
2,3,"411,000,000","560,622,615",Madonna,Sticky Sweet Tour a,85,"4,835,294",6.0,2008,2009
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,156,"2,546,795",7.0,2018,2019
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,53,"6,522,173",8.0,2018,2018
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,88,"3,467,709",9.0,2012,2012
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,131,"2,137,405",11.0,2008,2009
7,7,"257,600,000","257,600,000",Pink,Summer Carnival,41,"6,282,927",12.0,2023,2024
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,49,"5,226,215",13.0,2016,2016
9,10,"250,400,000","309,141,878",Taylor Swift,The World Tour,85,"2,945,882",14.0,2015,2015
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs Carter Show World Tour,132,"1,735,606",15.0,2013,2014
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour,203,"1,118,227",18.0,2009,2011
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,151,"1,350,993",19.0,2014,2015
13,14,"200,000,000","299,676,265",Cher,Living Proof The Farewell Tour a,325,"615,385",20.0,2002,2005
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,60,"3,233,333",5.0,2006,2006
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,142,"1,295,775",22.0,2013,2014
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,98,"1,734,694",NaN,2012,2013
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,82,"2,070,732",4.0,2015,2016
18,19,"167,700,000","204,486,106",Adele,Adele Live,121,"1,385,950",25.0,2016,2017
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,86,"1,744,186",26.0,2013,2014